version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    volumes:
      - .:/app

  db:
    image: postgres:13.14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${SQLALCHEMY_DATABASE_USER}
      POSTGRES_PASSWORD: ${SQLALCHEMY_DATABASE_PASSWORD}
      POSTGRES_DB: ${SQLALCHEMY_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
